"""The plain text output, one file per table."""

import os
import logging
import pandas as pd

logger = logging.getLogger(__name__)



def write_tsv(cellData: pd.DataFrame, geneData: pd.DataFrame, cellBoundaries: pd.DataFrame,
              out_dir: os.path) -> None:
    """Write all data files to output directory.

    Args:
        cellData: Cell data DataFrame
        geneData: Gene data DataFrame
        cellBoundaries: Cell boundaries DataFrame
        out_dir: path to output directory
    """
    out_dir = os.path.join(out_dir, 'tsv')
    if not os.path.exists(out_dir):
        os.makedirs(out_dir)

    # Save cell data
    cellData_path = os.path.join(out_dir, "cellData.tsv")
    cellData.to_csv(cellData_path, sep='\t', index=False)
    cellData_mb = os.path.getsize(cellData_path) / (1024 * 1024)
    logger.info('Saved at: %s (%.1f MB)', cellData_path, cellData_mb)

    # Save gene data
    geneData_path = os.path.join(out_dir, "geneData.tsv")
    geneData.to_csv(os.path.join(out_dir, 'geneData.tsv'), sep='\t', index=False)
    geneData_mb = os.path.getsize(geneData_path) / (1024 * 1024)
    logger.info('Saved at: %s (%.1f MB)', geneData_path, geneData_mb)

    # Save boundaries
    cellBoundaries_path = os.path.join(out_dir, "cellBoundaries.tsv")
    cellBoundaries.to_csv(cellBoundaries_path, sep='\t', index=False)
    cellBoundaries_mb = os.path.getsize(cellBoundaries_path) / (1024 * 1024)
    logger.info('Saved at %s: (%.1f MB)', cellBoundaries_path, cellBoundaries_mb)


def read_tsv(filepath):
    """
    Convenience function to read the tsv files generated by pciSeq
    """
    data = pd.read_csv(filepath, sep='\t')
    data = data.map(
        lambda x: eval(x) if isinstance(x, str) and x.strip().startswith(('{', '[', '(')) else x)
    return data
