import { defineConfig } from 'vitepress'
// the per-function list under "Functions" is generated by gen_api.py
import apiFunctions from './api-nav.json'

// Config for the pciSeq docs. We used to run this on Docusaurus but moved to
// VitePress. The site is served from a subpath on GitHub Pages, hence base.
export default defineConfig({
  title: 'pciSeq',
  description: 'Probabilistic cell typing by in situ sequencing',
  lang: 'en-US',

  // Project site at https://acycliq.github.io/pciSeq_3d/
  base: '/pciSeq_3d/',

  // keep the light/dark toggle. The site always starts light, whatever the reader's
  // operating system says, see the script in head below
  appearance: true,

  // don't die on a bad link while the docs are still being written
  ignoreDeadLinks: true,

  // generated table snippets that pages pull in with @include, not pages themselves.
  // the self-consistency appendix is hidden, not deleted: it is left out of the build here
  // and out of the sidebar below. The errata is built but not in the sidebar and nothing
  // links to it, so it can only be reached with its address, the-model/errata.html
  srcExclude: ['**/_tables/**', 'the-model/appendix-self-consistency.md'],

  head: [
    // start on the light theme even when the OS is dark. VitePress reads this key and
    // only falls back to the OS when nothing is stored, so writing 'light' once makes
    // light the default. The toggle still works and still remembers what the reader picks.
    ['script', {}, `try{localStorage.getItem('vitepress-theme-appearance')||localStorage.setItem('vitepress-theme-appearance','light')}catch(e){}`],
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/pciSeq_3d/favicon.svg' }],
    ['meta', { name: 'theme-color', content: '#10b981' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'pciSeq' }],
    ['meta', { property: 'og:description', content: 'Probabilistic cell typing by in situ sequencing' }],
  ],

  // turn on the built-in math (MathJax under the hood). needs the
  // markdown-it-mathjax3 dev dependency to be installed.
  markdown: {
    math: true,
  },

  themeConfig: {
    nav: [
      { text: 'Docs', link: '/' },
      { text: 'Running pciSeq', link: '/running-pciseq' },
      { text: 'How it works', link: '/how-it-works/overview' },
      { text: 'Explaining the calls', link: '/explaining-the-calls/overview' },
      { text: 'The model', link: '/the-model/overview' },
      { text: 'API', link: '/api/reference' },
    ],

    sidebar: [
      { text: 'Introduction', link: '/' },
      { text: 'Installation', link: '/installation' },
      {
        text: 'Running pciSeq',
        link: '/running-pciseq',
        items: [
          { text: 'From Python', link: '/running-pciseq' },
          { text: 'Fine-tuning', link: '/running-pciseq#fine-tuning' },
          { text: 'Command line', link: '/api/command-line' },
          { text: 'Live viewer', link: '/api/live-viewer' },
          { text: 'Working with results', link: '/api/working-with-results' },
          { text: 'SpatialData store', link: '/api/spatialdata-store' },
          { text: 'Working with the image', link: '/api/working-with-the-image' },
        ],
      },
      {
        text: 'How it works',
        link: '/how-it-works/overview',
        items: [
          { text: 'Overview', link: '/how-it-works/overview' },
          { text: '1. Misread density', link: '/how-it-works/misread-density' },
          {
            text: '2. Warping the cell type definitions',
            link: '/how-it-works/warping-the-reference',
            // the demo hangs off this one, so it sits indented under it
            items: [
              { text: '2a. Demo: the scaling factors', link: '/how-it-works/scale-factors-demo' },
            ],
          },
          { text: '3. Cell to class', link: '/how-it-works/cell-to-celltype' },
          { text: '4. Spots to cells', link: '/how-it-works/spots-to-cells' },
        ],
      },
      {
        text: 'Explaining the calls',
        link: '/explaining-the-calls/overview',
        items: [
          { text: 'Overview', link: '/explaining-the-calls/overview' },
          { text: "How a cell's call was made", link: '/explaining-the-calls/why-a-cell-got-its-type' },
          { text: "How a spot's call was made", link: '/explaining-the-calls/why-a-spot-got-its-cell' },
        ],
      },
      {
        text: 'The model',
        link: '/the-model/overview',
        items: [
          { text: 'Overview', link: '/the-model/overview' },
          { text: 'Misread density', link: '/the-model/misread-density' },
          { text: 'Scale factors', link: '/the-model/scale-factors' },
          { text: 'Cell-class assignment', link: '/the-model/cell-class' },
          { text: 'Spot assignment', link: '/the-model/spot-assignment' },
          // hidden for now, see srcExclude above
          // { text: 'Errata', link: '/the-model/errata' },
          // { text: 'Appendix: self-consistency', link: '/the-model/appendix-self-consistency' },
        ],
      },
      {
        text: 'API reference',
        link: '/api/reference',
        items: [
          {
            text: 'Functions',
            link: '/api/reference',
            collapsed: true,
            items: apiFunctions,
          },
          { text: 'Configuration (opts)', link: '/api/configuration' },
        ],
      },
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/acycliq/pciSeq_3d' },
    ],

    editLink: {
      pattern: 'https://github.com/acycliq/pciSeq_3d/edit/dev_3d/website/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Built with VitePress.',
      copyright: 'Copyright © 2026 acycliq',
    },

    search: {
      provider: 'local',
    },
  },
})